### ISSUE TITLE
Bug: If player leaves room before game start, they don't have a position, and this causer error.

### ISSUE THREAD

**Issue by JamesOwers** [RyanrDavies/curvytron-client#10]
to reproduce, join a game you start and then leave (to spectate)
```
$ python heuristic_agent.py 
server: 129.215.91.49:8080 room: room_room_5291
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/james/anaconda2/envs/rlhack/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "heuristic_agent.py", line 209, in run
    state = self.env.reset()
  File "/home/james/git/forks/curvytron-client/curvytron.py", line 58, in reset
    return State(self.client.get_canvas(), self.client.position, self.client.angle)
  File "/home/james/git/forks/curvytron-client/client.py", line 168, in get_canvas
    draw_x, draw_y = self.game.players[player].draw_position
TypeError: 'NoneType' object is not iterable
```

**Comment by JamesOwers** [comment]
....no idea what happened there. Seems fixed!
